name: "Patchkit Actions - Publish"

description: "Use Patchkit CLI tools in Github Actions to publish existing draft releases"

branding:
  icon: "arrow-up"
  color: "gray-dark"

inputs:
  secret:
    description: "Application secret"
    required: true
  api-key:
    description: "User API key"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Patchkit Tools
      uses: Battle-Nations/Patchkit-Actions/setup@v2

    - name: Run Patchkit Tools Publish
      uses: knicknic/os-specific-run@v1
      with:
        macos: ./patchkit-tools publish-version --secret "${{ inputs.secret }}" --api-key "${{ inputs.api-key }}" --draft --wait
        linux: ./patchkit-tools publish-version --secret "${{ inputs.secret }}" --api-key "${{ inputs.api-key }}" --draft --wait
        windows: ./patchkit-tools publish-version --secret "${{ inputs.secret }}" --api-key "${{ inputs.api-key }}" --draft --wait
