name: "Patchkit Actions - Setup"

description: "Sets up Patchkit CLI tools in Github Actions"

branding:
  icon: "arrow-up"
  color: "gray-dark"

runs:
  using: "composite"
  steps:

    - name: Get latest version tag
      run: echo "::set-output name=PATCHKIT_VERSION::$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/patchkit-net/patchkit-tools/releases/latest | cut -d'/' -f8)"
      id: patchkit-version
      shell: bash

    - name: Download latest Patchkit Tools
      uses: knicknic/os-specific-run@v1
      with:
        macos: curl -L https://github.com/patchkit-net/patchkit-tools/releases/download/${{ steps.patchkit-version.outputs.PATCHKIT_VERSION }}/patchkit-tools-osx.zip -o patchkit-tools.zip
        linux: curl -L https://github.com/patchkit-net/patchkit-tools/releases/download/${{ steps.patchkit-version.outputs.PATCHKIT_VERSION }}/patchkit-tools-linux-x86_64.zip -o patchkit-tools.zip
        windows: curl -L https://github.com/patchkit-net/patchkit-tools/releases/download/${{ steps.patchkit-version.outputs.PATCHKIT_VERSION }}/patchkit-tools-x86_64-win32.zip -o patchkit-tools.zip
        windowsShell: 'bash'

    - run: unzip -q patchkit-tools.zip
      shell: bash
